#!/bin/bash
# проверили два ли элемента подалось, если нет, то выводит ошибку
if [ "$#" -ne 2 ]; then
    echo "Usage: $0 <input_directory> <output_directory>"
    exit 1
fi
# присвоили два аргумента
INPUT_director=$1
OUTPUT_director=$2
# проверяем на существование этих двух элементов
if [ ! -d "$INPUT_director" ]; then
    echo "Input directory does not exist"
    exit 1
fi

if [ ! -d "$OUTPUT_director" ]; then
    echo "Output directory does not exist"
    exit 1
   
fi
# находим все файлы в указанном в первом аргументе  и копируем их во второй аргумент, используя команду cp.
find "$INPUT_director" -type f -exec cp {} "$OUTPUT_director" \;
